SELECT
A.MEM_NAME,
C.SCH_NAME,
B.SFUND_VALUE
FROM SCHAR_FUND B , MEMBER A, SCHOLARSHIP C
WHERE A.MEM_ID = B.SFUND_STUDENT
AND B.SFUND_GETDATE IS NOT NULL
AND B.SFUND_SMST = (SELECT CODE_NAME FROM CODE WHERE GROUP_CODE = 'A00')
AND C.SCH_CODE = B.SCHAR_CODE


;



SELECT B.DEP_NAME
FROM MEMBER A,DEPARTMENT B
WHERE A.MEM_ID ='1911005'
AND A.DEP_NO =B.DEP_NO

;

SELECT A.PAY_AMOUNT AS ³³ºÎ±Ý¾×,

FROM PAY_TUITION A

;
	SELECT 
			A.PAY_EXCPECT,
			B.SFUND_VALUE,
			A.PAY_CHECK,
			A.PAY_DIVISION 
		FROM PAY_TUITION A, SCHAR_FUND B
		WHERE A.MEM_ID = '1911005'
		  AND A.PAY_NUMBER ='1'
		  AND B.SFUND_STUDENT =A.MEM_ID 
		  AND A.SMST = (SELECT CODE_NAME FROM CODE WHERE GROUP_CODE = 'A00')
		  AND A.SMST = B.SFUND_SMS

;

SELECT PAY_ACN,PAY_BANK
FROM PAY_TUITION
WHERE MEM_ID='1911005'
 AND SMST = (SELECT CODE_NAME FROM CODE WHERE GROUP_CODE = 'A00')
AND PAY_NUMBER='1'



SELECT DEP_NAME
FROM DEPARTMENT
WHERE DEP_NO='510'





