   2020-07-21-02)SQL의 기초
   
   1)역사 
    - 1973 : SQUARE
    - 1974 : Ststem R용의 SEQUEL
    - 1980 : SQL로 명칭 변경
    - 1988 : ANSI, ISO 국제 표준으로 제정
    - 1989 : SQL-1(SQL/89) 표준안 제정
    - 1992 : SQL-2 , 1999 : SQL-3 표준안 제정
    
    2)SQL 명령의 분류
    (1) DDL (DATA DEFINITION LANGUAGE) : CREATE, DROP, ALTER
    (2) DCL (DATA CONTROL LANGUAGE) : GRANT, REVOKE, COMMIT, ROLLBACK
    (3) DML (DATA MANIPULATION LANGUAGE) : INSERT, UPDATE, DELETE
    (4) Query : SELECT
    
    3)SQL 언어의 특징
    - 구조적 언어이기 때문에 변수/상수, 비교문, 반복문, 분기문이 없음